D8 un 891
dof-dss/nicsdru_unity pull request #1023
Opened 2022-01-14 11:11 UTC by soda736

2022-01-14 14:58 UTC, ooneill547 approved these changes

2022-01-14 15:43 UTC, omahm commented on web/sites/pbni/themes/pbni_theme/templates/views/views-view-unformatted--search-result-page.html.twig
> +    set row_classes = [
I'd move this outside the row loop

2022-01-17 09:18 UTC, soda736 commented on web/sites/pbni/themes/pbni_theme/templates/views/views-view-unformatted--search-result-page.html.twig
> +    set row_classes = [
I've fixed these templates across Unity.

2022-01-18 09:07 UTC, johangant requested changes
There are a number of settings and config values that should come from environment variables to avoid leaking the more sensitive things (site hash value) or just to avoid repetition (DB creds)

2022-01-18 09:07 UTC, johangant commented on web/sites/default/settings.php
> +$settings['hash_salt'] = 'dgVeucwlf22lXD_tZaEPZ4q_7Fbb0Q-OoDkqdv1FwTAUvJlSt6SiLCExq6bhmkkGj8mhlea3nA';
This value should, ideally, be kept as an environment variable.

2022-01-18 09:07 UTC, johangant commented on web/sites/default/settings.php
> +$settings['config_sync_directory'] = 'sites/default/files/config_aNJz9uTjokJEANnoHYx7eGWeylVqKYsxSDt-WT08GrvQiKiD7f5LDuN-kQeB5xmE7sHcqVwgDg/sync';
Looks like a default value from install. Should be an environment variable or at least something like `../config/<sitename>/sync`

2022-01-18 09:07 UTC, johangant commented on web/sites/default/settings.php
> +$databases['default']['default'] = array (
The raw values here shouldn't be set like this. These settings can/should be set once and reference environment variables, which can be different from Lando to PSH, as required.

2022-01-18 09:26 UTC, johangant approved these changes
Unwanted settings files look gone, so all good :+1:

2022-01-18 09:27 UTC, merged