D8UN-1008 PCSPS: Create pcsps migration module
dof-dss/nicsdru_unity pull request #1172
Opened 2022-03-02 14:51 UTC by ooneill547

2022-03-02 16:04 UTC, soda736 commented on config/pcsps/config/core.extension.yml
> +  migrate_absolute_links: 0
We don't want to export this module.

2022-03-02 16:07 UTC, soda736 requested changes
Martin said we want to get rid of alot of migration files. Mainly anything that has "field" in them as we never want to run those again. Check other migration modules and omit migration files from this module.

2022-03-23 16:04 UTC, David-Corbett approved these changes

2022-04-15 10:06 UTC, soda736 approved these changes
LG

2022-04-15 10:06 UTC, merged