D8UN-139 Create and style vacancy view page
dof-dss/nicsdru_unity pull request #150
Opened 2020-09-15 17:36 UTC by ooneill547

Vacancy view page was created and styled to appear like the live site. 
I had to install the block visibility groups module to allow for more configuration of the sidemenu to display where appropriate.
Title and breadcrumb nav were also inserted into the vacancy view and vacancy node pages.

2020-09-16 08:16 UTC, DuttonMa requested changes
All looks good, just the one comment

2020-09-16 08:16 UTC, DuttonMa commented on config/uregni/config/core.extension.yml
> +  config_inspector: 0
I think that 'config_inspector' here is probably a mistake and that you were just using it locally ?
If you do mean to include it in the build then you'll need to add it to composer too and make sure that it is only installed  on 'local' builds - not on platform.

2020-09-16 09:06 UTC, ooneill547 commented on config/uregni/config/core.extension.yml
> +  config_inspector: 0
I removed it but forgot to push core.extension when I pushed composer. I'll fix it now.

2020-09-18 11:11 UTC, DuttonMa commented on config/uregni/config/core.extension.yml
> +  config_inspector: 0
All looks good now

2020-09-18 11:11 UTC, DuttonMa approved these changes
Looks good to me

2020-09-18 11:23 UTC, merged