D8 un 137
dof-dss/nicsdru_unity pull request #157
Opened 2020-09-18 10:45 UTC by soda736

2020-09-18 11:54 UTC, johangant requested changes
I'd encourage not using `!important` wherever possible

2020-09-18 11:54 UTC, johangant commented on web/sites/uregni/themes/uregni_theme/src/scss/components.scss
> +      float: left !important;
Hmm. Is there a better way of reducing the need for `!important` here? Maybe increase the specificity of selectors or even use an ID attribute to get this to take priority? `!important` will otherwise mess about with the priorities of layered CSS rules making longer-term maintenance much harder.

2020-09-18 14:47 UTC, soda736 commented on web/sites/uregni/themes/uregni_theme/src/scss/components.scss
> +      float: left !important;
I was using !important to override another !important. I have now amended the page.html.twig to match D7 and this gave me another ID attribute to use and reduce the need for !important declaration.

2020-09-22 09:15 UTC, johangant approved these changes
Cheers @soda736... always a pain when `!important` enters the scene but if that's what you're working against then any improvement's a good one.

2020-09-22 10:08 UTC, merged