D8 un 272
dof-dss/nicsdru_unity pull request #266
Opened 2021-01-07 14:28 UTC by soda736

2021-01-11 10:09 UTC, johangant commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +            if (preg_match('/(.*) (\(([A-Z|a-z]*) ([0-9]*\D?[0-9]*) ([A-Z]*)\))/', $decode_string, $match2)) {
At this level of depth in a function + the complexity of the regex, I'd highly recommend some code comments to annotate this to both give some context and even some representative examples of where/how this applies.

2021-01-11 10:13 UTC, DuttonMa requested changes
This is good work, not an easy task to take the body field apart and reconstruct it in this way !
I'm sure that the functionality works well but have added a few suggestions that will make the code more robust and readable for others.

2021-01-11 10:13 UTC, DuttonMa commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +            $decode_string = str_replace('&nbsp;', ' ', $strip_tags);
Think it would be better to use something like html_entity_decode() her to catch other html entities

2021-01-11 10:13 UTC, DuttonMa commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +        $body_text = &$variables['items'][0]['content']['#text'];
This is a good use of a reference variable !

2021-01-11 10:14 UTC, johangant approved these changes
Solid stuff. I think it would benefit from some code comments as from an initial look in, it's quite tricky to frame the field preprocess in a given context

2021-01-15 14:31 UTC, soda736 commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +  if ($variables['element']['#bundle'] == 'publication_page') {
I've added a description for the function.

2021-01-15 14:33 UTC, soda736 commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +            if (preg_match('/(.*) (\(([A-Z|a-z]*) ([0-9]*\D?[0-9]*) ([A-Z]*)\))/', $decode_string, $match2)) {
I've added comments and an example to try and describe the regex and what it does.

2021-01-15 14:34 UTC, soda736 commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +            if (preg_match('/(.*) (\(([A-Z|a-z]*) ([0-9]*\D?[0-9]*) ([A-Z]*)\))/', $decode_string, $match2)) {
I've added an example and changed the variable name from $match2 to $file_description_matches.

2021-01-15 14:36 UTC, soda736 commented on web/sites/uregni/themes/uregni_theme/uregni_theme.theme
> +            $decode_string = str_replace('&nbsp;', ' ', $strip_tags);
After our chat I switched the functions so that html_entity_decode() ran before stip_tags() and this reduced the need for the str_replace().

2021-01-18 11:39 UTC, DuttonMa approved these changes
Well done for making the changes - looks great now !

2021-01-18 11:42 UTC, merged