new facet drilldown contrib module
dof-dss/nicsdru_unity pull request #279
Opened 2021-01-22 15:55 UTC by DuttonMa

As discussed in the team meeting, this is the new facet drilldown contrib module that has been written by Orla, Adam and me.

We do not intend to merge this PR, but it is a good way to ask people to review it and to collect any feedback. Any changes that result from comments on this PR will be pushed up to drupal.org.

2021-01-26 13:39 UTC, johangant approved these changes
LGTM. Plenty of parts to this. I could only really chime in on some parts that felt a bit complex to read/comprehend that might benefit from refactoring a little, and some other minor stuff.

2021-01-26 13:39 UTC, johangant commented on web/modules/custom/date_facet_drilldown/date_facet_drilldown.module
> +      if (isset($procs['date_facet_drilldown'])) {
I usually recommend the use of `empty` over `isset` because the latter can evaluate to true if, say, a variable or array key is instantiated rather than checking whether it has a non-null value. I can see `empty` is used further up in the fucntion too for a similar check.

2021-01-26 13:39 UTC, johangant commented on web/modules/custom/date_facet_drilldown/date_facet_drilldown.module
> +  if (!empty($variables["facet"])) {
A personal opinion here: six levels of conditional code is usually a flag for me to stop and consider whether I can refactor to combine simpler checks, provide some early 'short circuits' or quick exit options at the start of the function, or encapsulate complex parts into their own functions to make it easier to comprehend.

2021-01-26 13:39 UTC, johangant commented on web/modules/custom/date_facet_drilldown/date_facet_drilldown.module
> +              $params = preg_replace('|' . $url_alias . '\/\d{4}-\d{2}|', '', $params);
+1 for using a regex delimiter that isn't a forward slash! Makes it much easier to read when there are multiple, escaped slash characters in the pattern already.

2021-01-26 13:41 UTC, omahm requested changes
Good job 👍  
There's a constructor in there that isn't really needed.

2021-01-26 13:41 UTC, omahm commented on web/modules/custom/date_facet_drilldown/src/Plugin/facets/query_type/SearchApiDateFacetDrilldown.php
> +  public function __construct(array $configuration, $plugin_id, $plugin_definition) {
Shouldn't need this as all it's doing is calling the parent constructor.

2021-01-28 14:37 UTC, DuttonMa commented on web/modules/custom/date_facet_drilldown/src/Plugin/facets/query_type/SearchApiDateFacetDrilldown.php
> +  public function __construct(array $configuration, $plugin_id, $plugin_definition) {
Good point, removing that

2021-01-28 14:42 UTC, DuttonMa commented on web/modules/custom/date_facet_drilldown/date_facet_drilldown.module
> +  if (!empty($variables["facet"])) {
Have now broken out to a separate function

2021-01-28 14:44 UTC, DuttonMa commented on web/modules/custom/date_facet_drilldown/date_facet_drilldown.module
> +      if (isset($procs['date_facet_drilldown'])) {
Fair enough, have changed that

2021-11-17 15:55 UTC, closed without merging