D8UN-315 set up basic page
dof-dss/nicsdru_unity pull request #343
Opened 2021-03-15 16:59 UTC by ooneill547

2021-03-16 08:41 UTC, soda736 approved these changes
LG

2021-03-16 12:22 UTC, DuttonMa requested changes
Just one module to uninstall, otherwise looks great

2021-03-16 12:22 UTC, DuttonMa commented on config/odscni/config/core.extension.yml
> +  unity_file_migrations: 0
We shouldn't install any migration modules in config, as we don't want them to be installed on any Platform.sh sites, we just need to install them locally when we're working with migrations (see Uregni).

2021-03-22 15:52 UTC, ooneill547 commented on config/odscni/config/core.extension.yml
> +  unity_file_migrations: 0
This has now been removed

2021-03-22 16:01 UTC, soda736 approved these changes
Looks good

2021-03-22 16:06 UTC, DuttonMa approved these changes

2021-03-22 16:27 UTC, merged