D8 un 588
dof-dss/nicsdru_unity pull request #613
Opened 2021-06-30 13:53 UTC by soda736

Search page templates, preprocessing and regions.

2021-06-30 14:32 UTC, ooneill547 approved these changes

2021-06-30 14:33 UTC, omahm requested changes
Looks good overall. A few wee suggestions..  ping me if you want to go over in_array

2021-06-30 14:33 UTC, omahm commented on web/sites/niauditoffice/themes/niauditoffice_theme/niauditoffice_theme.theme
> +    if ($variables['page']['#title'] == $search_page) {
This works but take a look at https://www.php.net/manual/en/function.in-array.php
Could replace 5 lines with 1.

2021-06-30 14:33 UTC, omahm commented on web/sites/niauditoffice/themes/niauditoffice_theme/templates/views/views-view-unformatted--search-result-page.html.twig
> +    set row_classes = [
row_classes will be set with every look of the rows, I'd create this outside the loop

2021-06-30 19:06 UTC, soda736 commented on web/sites/niauditoffice/themes/niauditoffice_theme/templates/views/views-view-unformatted--search-result-page.html.twig
> +    set row_classes = [
I am trying to add the search result class to every article in the view. There is code for this in the other unity sites and styling in place for the .search-results. Would it be better to have the search result class outside of the rows and add the styling to .search-results article?

2021-06-30 19:06 UTC, soda736 commented on web/sites/niauditoffice/themes/niauditoffice_theme/niauditoffice_theme.theme
> +    if ($variables['page']['#title'] == $search_page) {
Think I know what you mean, I've made a change to it.

2021-07-01 07:56 UTC, omahm approved these changes
Yup, that's it. Good stuff

2021-07-01 08:41 UTC, merged