D8UN-623 Add current page to all breadcrumb links
dof-dss/nicsdru_unity pull request #669
Opened 2021-07-23 16:44 UTC by ooneill547

This needed to be completed for all unity sites

2021-07-27 10:00 UTC, omahm requested changes
Generally looks good, just a couple of issues.

2021-07-27 10:00 UTC, omahm commented on web/sites/fiscalcommissionni/modules/custom/fiscalcommissionni_breadcrumbs/src/PageBreadcrumb.php
> +    if ($this->node) {
Shouldn't really need this check as build will only get called if we have passed the applies() call

2021-07-27 16:13 UTC, ooneill547 commented
> Generally looks good, just a couple of issues.

I have updated the fiscal commission breadcrumbs to check if it's correct and then I will do the rest

2021-07-28 15:16 UTC, johangant commented
I think this could do with an update/merge from `development` to assess what has changed; there are a number of things that look like they come from other feature branches and should already be in `development` by now.

2021-08-02 09:45 UTC, omahm approved these changes
Looks good

2021-08-02 10:30 UTC, merged