D8UN-653 Fiscal Council: Add sidemenu
dof-dss/nicsdru_unity pull request #698
Opened 2021-08-13 15:26 UTC by ooneill547

2021-08-15 19:07 UTC, omahm requested changes
Mostly ok but just need to replace the str_contains call.

2021-08-15 19:07 UTC, omahm commented on web/sites/nifiscalcouncil/themes/nifiscalcouncil_theme/nifiscalcouncil_theme.theme
> +      if (str_contains($plugin_id, $search_page)) {
This is a PHP 8 method and you won't be able to use this on the site (7.4). I'd suggest using strpos.

2021-08-24 11:48 UTC, ooneill547 commented on web/sites/nifiscalcouncil/themes/nifiscalcouncil_theme/nifiscalcouncil_theme.theme
> +      if (str_contains($plugin_id, $search_page)) {
I removed this section of code because it wasn't actually being used in this site.

2021-08-24 15:08 UTC, omahm approved these changes
LG

2021-08-24 15:15 UTC, merged