D8UN-643 OCTF: Style news page
dof-dss/nicsdru_unity pull request #750
Opened 2021-09-09 16:25 UTC by ooneill547

2021-09-10 10:25 UTC, johangant commented on web/sites/octf/themes/octf_theme/octf_theme.theme
> +  if (isset($variables['element']['#view_mode'])) {
Contrib and core code tends to prefer `empty()` over `isset()` as the latter can still return true for a value like 0, because the variable has been set/initialised. Empty provides a more robust check for 'truthiness' or nulls.

See https://www.drupal8.ovh/en/tutoriels/228/isset-vs-empty-vs-null

2021-09-10 11:50 UTC, johangant requested changes
A nitpick but I'd recommend switching the `isset()` call to `empty()` for fewer unexpected truthy evaluations in future. Otherwise, great!

2021-09-10 14:58 UTC, ooneill547 commented on web/sites/octf/themes/octf_theme/octf_theme.theme
> +  if (isset($variables['element']['#view_mode'])) {
Thanks, I'll create a ticket to change this on the other sites.

2021-09-16 11:45 UTC, johangant approved these changes

2021-09-16 11:52 UTC, merged